name: Smoke Test

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: "test suite name"
        required: true
        default: "Smoke"
  # push:
  #   branches:
  #     - main
  #     - dev

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable || sudo apt-get install -y chromium-browser


      - name: Run Smoke Tests
        run: |
          mvn clean test -Dsuite=Smoke
          
      - name: Upload Smoke Test Results
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: target/surefire-reports/
